version: 2
build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
python:
  install:
    - requirements: requirements_docs.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
        - perf
        - ml
        - stac
sphinx:
  configuration: doc/source/conf.py
conda:
  environment: environment.yml
formats: []
