version: 2
build:
    image: latest
python:
    version: 3.7
    install:
      - requirements: requirements.txt
      - method: pip
        path: .
        extra_requirements:
            - docs
      - method: setuptools
sphinx:
    configuration: doc/source/conf.py
