version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - libgdal-dev
    - gdal-bin
    - python3-gdal

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: doc/source/conf.py
  builder: html
  fail_on_warning: false

formats: []
