name: gwenv
channels:
- defaults
dependencies:
- python=3.8.12
- Cython>=0.29.*
- numpy>=1.19.0
- setuptools>=59.5.0
- ipython
- libspatialindex
- libgdal=3.0.2
- gdal=3.0.2
- pip>=22.2.2
- pip:
  - -r requirements_docs.txt
