"""Generate notebooks/object_detection.ipynb.

Run with: ``python notebooks/_build_object_detection_ipynb.py``.

This generator exists because hand-writing nested JSON is error-prone.
The output notebook is checked in alongside the generator so end users
do not need to run it.
"""

import json
from pathlib import Path


def md(*lines):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": _to_source(lines),
    }


def code(*lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _to_source(lines),
    }


def _to_source(lines):
    text = "\n".join(lines)
    parts = text.split("\n")
    # Jupyter stores source as a list where every line except the last
    # has a trailing newline.
    out = []
    for i, p in enumerate(parts):
        if i < len(parts) - 1:
            out.append(p + "\n")
        else:
            out.append(p)
    return out


CELLS = []

CELLS.append(md(
    "# Object Detection with geowombat",
    "",
    "This notebook walks through the geowombat object-detection module:",
    "",
    "1. **Quickstart** — run a pretrained YOLO model on a public satellite",
    "   detection benchmark (NWPU VHR-10 via TorchGeo) and score its accuracy.",
    "2. **Geowombat-native workflow** — fetch a NAIP aerial image from",
    "   Microsoft Planetary Computer plus OpenStreetMap building footprints,",
    "   build a YOLO training dataset, run inference, score it, and export a",
    "   GeoPackage you can review feature-by-feature in QGIS (e.g. with the",
    "   GoToNextFeature3+ plugin).",
    "3. **Optional fine-tuning** — fine-tune YOLO on the dataset built in",
    "   step 2 so detections are actually useful for buildings.",
    "4. **Refine boxes to polygons with SAM** — turn the fine-tuned",
    "   bounding-box detections into precise vector footprints using",
    "   Meta's Segment Anything Model.",
    "",
    "Required installs:",
    "",
    "```",
    "pip install geowombat[dl,detect,sam,stac]",
    "pip install osmnx torchgeo",
    "```",
))

CELLS.append(md(
    "## Setup",
))

CELLS.append(code(
    "import warnings",
    "from pathlib import Path",
    "",
    "import geopandas as gpd",
    "import matplotlib.pyplot as plt",
    "import numpy as np",
    "",
    "import geowombat as gw",
    "from geowombat.detect import (",
    "    YOLODetector,",
    "    boxes_from_polygons,",
    "    build_dataset,",
    "    detection_accuracy,",
    "    export_for_review,",
    "    plot_detections,",
    "    predict,",
    ")",
    "",
    "warnings.filterwarnings('ignore')",
    "WORK_DIR = Path('object_detection_demo')",
    "WORK_DIR.mkdir(exist_ok=True)",
))

# ---------------- Section A ----------------
CELLS.append(md(
    "## 1. Quickstart: pretrained YOLO on NWPU VHR-10",
    "",
    "[NWPU VHR-10](https://gcheng-nwpu.github.io/) is a small (~715 images,",
    "10 classes) public satellite-imagery detection benchmark. TorchGeo",
    "auto-downloads it. We'll run a pretrained Ultralytics YOLO model on a",
    "few images and score the result.",
    "",
    "**Caveat:** YOLO's default weights are trained on COCO, which only",
    "overlaps with VHR-10 on a couple of classes (e.g. *airplane*, *ship*,",
    "*vehicle*). Expect low mAP — this section is about exercising the",
    "API, not about state-of-the-art accuracy. The geowombat-native section",
    "below shows the full train-and-score loop.",
))

CELLS.append(code(
    "from torchgeo.datasets import VHR10",
    "",
    "vhr_dir = WORK_DIR / 'vhr10'",
    "ds = VHR10(root=str(vhr_dir), split='positive', download=True)",
    "print(f'Dataset size: {len(ds)} positive images')",
    "print('Classes:', ds.categories[:5], '...')",
))

CELLS.append(code(
    "# Inspect a single sample. TorchGeo 0.9 keys: image, label, bbox_xyxy, mask",
    "sample = ds[0]",
    "img = sample['image'].permute(1, 2, 0).numpy().astype(np.uint8)",
    "boxes = sample['bbox_xyxy'].numpy()",
    "labels = sample['label'].numpy()",
    "",
    "fig, ax = plt.subplots(figsize=(8, 8))",
    "ax.imshow(img)",
    "for (x1, y1, x2, y2), lbl in zip(boxes, labels):",
    "    ax.add_patch(plt.Rectangle((x1, y1), x2-x1, y2-y1,",
    "                               fill=False, edgecolor='yellow', lw=2))",
    "    ax.text(x1, y1-3, ds.categories[lbl], color='yellow', fontsize=8)",
    "ax.set_title('NWPU VHR-10 sample with ground-truth boxes')",
    "ax.axis('off')",
    "plt.show()",
))

CELLS.append(md(
    "### Picking a YOLO variant",
    "",
    "Ultralytics ships several pretrained YOLO weight families. The right",
    "choice depends on **what you're detecting**, not just how fast you",
    "need it to run.",
    "",
    "| Weight family | Trained on | Classes | When to use |",
    "|---|---|---|---|",
    "| `yolov8{n,s,m,l,x}.pt` | COCO | 80 everyday classes (person, car, dog, ...) | Ground-level photos. **Wrong tool for overhead imagery** — most COCO classes never appear from above. |",
    "| `yolo11{n,s,m,l,x}.pt` | COCO | Same 80 classes | Newer architecture, same training set as YOLOv8 COCO. Same caveat for aerial data. |",
    "| `yolov8{n,s,m,l,x}-obb.pt` | **DOTA-v1** (aerial) | 15 aerial classes: *plane, ship, storage tank, baseball diamond, tennis court, basketball court, ground track field, harbor, bridge, large vehicle, small vehicle, helicopter, roundabout, soccer ball field, swimming pool* | **Best out-of-the-box choice for satellite/aerial imagery**. Predicts rotated boxes (OBB). |",
    "| `yolov8{s,m,l,x}-worldv2.pt` | LVIS + grounding | **Open-vocabulary** — you pass text prompts at inference time | When DOTA classes don't cover what you need. Use `model.set_classes(['airplane', 'truck', ...])` before predicting. |",
    "| Custom-trained checkpoint | Your dataset | Whatever you trained on | After fine-tuning — see Section 3 below. |",
    "",
    "Size suffix (`n` < `s` < `m` < `l` < `x`) trades inference speed for",
    "accuracy. Default to `n` or `s` for prototyping, `m`+ for production.",
    "",
    "**Non-YOLO option**: ``geowombat.detect.TorchGeoDetector`` wraps",
    "torchvision Faster R-CNN / RetinaNet and can load TorchGeo's xView",
    "pretrained weights — a richer 60-class aerial label set. Use it when",
    "the AGPL license on Ultralytics is a problem or when xView's class",
    "set is a better fit than DOTA's.",
))

CELLS.append(code(
    "# 1. Default `yolov8n.pt` — trained on COCO, the wrong tool for overhead",
    "# imagery. We expect garbage detections (a 'train' box covering the",
    "# entire chip, etc.) because COCO classes don't generalize.",
    "from ultralytics import YOLO",
    "",
    "# Load the smallest YOLOv8 weights (auto-downloaded on first run).",
    "yolo_coco = YOLO('yolov8n.pt')",
    "result = yolo_coco.predict(",
    "    source=img,        # the image to run on",
    "    conf=0.1,          # keep detections above this confidence",
    "    verbose=False,",
    ")[0]                   # one image in, one result out",
    "",
    "fig, ax = plt.subplots(figsize=(8, 8))",
    "ax.imshow(img)",
    "if result.boxes is not None and len(result.boxes) > 0:",
    "    for b, c, s in zip(result.boxes.xyxy.cpu().numpy(),",
    "                       result.boxes.cls.cpu().numpy().astype(int),",
    "                       result.boxes.conf.cpu().numpy()):",
    "        x1, y1, x2, y2 = b",
    "        ax.add_patch(plt.Rectangle((x1, y1), x2-x1, y2-y1,",
    "                                    fill=False, edgecolor='red', lw=2))",
    "        ax.text(x1, y1-3, f'{yolo_coco.names[c]} {s:.2f}',",
    "                color='red', fontsize=8)",
    "ax.set_title('YOLOv8n (COCO weights) on VHR-10 — note the misfires')",
    "ax.axis('off')",
    "plt.show()",
))

CELLS.append(md(
    "### Improved: DOTA-pretrained YOLO-OBB",
    "",
    "Same model architecture, different training data. `yolov8n-obb.pt`",
    "was trained on **DOTA-v1**, a satellite/aerial benchmark with the",
    "15 classes listed above. It produces **oriented bounding boxes**",
    "(four corner points each) instead of axis-aligned rectangles, which",
    "is what you want for objects on a runway, ship in a harbor, etc.",
    "",
    "On the same VHR-10 chip you should now see clean *plane* detections",
    "with reasonable confidence — no fine-tuning required.",
))

CELLS.append(code(
    "# 2. yolov8n-obb.pt — DOTA-trained. Same call, different weights.",
    "import matplotlib.patheffects as pe",
    "",
    "# `-obb.pt` weights predict rotated boxes instead of axis-aligned ones.",
    "yolo_obb = YOLO('yolov8n-obb.pt')",
    "result_obb = yolo_obb.predict(",
    "    source=img,",
    "    conf=0.25,     # this model is more confident, so we can raise the threshold",
    "    verbose=False,",
    ")[0]",
    "",
    "fig, ax = plt.subplots(figsize=(8, 8))",
    "ax.imshow(img)",
    "if result_obb.obb is not None and len(result_obb.obb) > 0:",
    "    quads = result_obb.obb.xyxyxyxy.cpu().numpy()  # (N, 4, 2)",
    "    clses = result_obb.obb.cls.cpu().numpy().astype(int)",
    "    confs = result_obb.obb.conf.cpu().numpy()",
    "    for quad, cls, conf in zip(quads, clses, confs):",
    "        polygon = plt.Polygon(quad, fill=False, edgecolor='lime', lw=2)",
    "        ax.add_patch(polygon)",
    "        cx, cy = quad.mean(axis=0)",
    "        ax.text(cx, cy, f'{yolo_obb.names[cls]} {conf:.2f}',",
    "                color='lime', fontsize=10, ha='center',",
    "                path_effects=[pe.withStroke(linewidth=2,",
    "                                            foreground='black')])",
    "ax.set_title('YOLOv8n-OBB (DOTA weights) on VHR-10 — proper aerial classes')",
    "ax.axis('off')",
    "plt.show()",
))

CELLS.append(md(
    "Same `YOLODetector` interface, just point ``weights=`` at the OBB",
    "checkpoint and set ``oriented=True`` (auto-detected from the filename",
    "ending in ``-obb.pt``). It then plugs into ``src.gw.detect`` exactly",
    "like the COCO variant — but the resulting ``GeoDataFrame`` carries",
    "rotated polygon geometries instead of axis-aligned boxes:",
    "",
    "```python",
    "from geowombat.detect import YOLODetector",
    "",
    "det = YOLODetector(weights='yolov8n-obb.pt')   # oriented=True inferred",
    "with gw.open('aerial.tif') as src:",
    "    preds = src.gw.detect(det, conf=0.25)",
    "```",
))

CELLS.append(md(
    "## 2. Geowombat-native workflow: NAIP + OpenStreetMap buildings",
    "",
    "Now the full pipeline using a *georeferenced* raster and *georeferenced*",
    "vector labels:",
    "",
    "1. Pull a NAIP scene from Microsoft Planetary Computer for a small AOI.",
    "2. Pull OSM building footprints for the same AOI with `osmnx`.",
    "3. Build a YOLO-format training dataset with `build_yolo_dataset`.",
    "4. Run inference; observe that COCO-pretrained YOLO won't see buildings.",
    "5. Score with `detection_accuracy` and export a review GeoPackage.",
    "6. Optional: fine-tune YOLO on the dataset from step 3.",
))

CELLS.append(code(
    "# AOI: ~2 km square over Capitol Hill, Washington DC. Row-house",
    "# residential gives the fine-tune cell good signal (dense, regular,",
    "# visually distinctive buildings). Adjust the bounds for any other",
    "# city — wider bounds give more training data but a slower download.",
    "from shapely.geometry import box as shapely_box",
    "",
    "AOI_BOUNDS = (-77.012, 38.882, -77.000, 38.898)  # west, south, east, north (~1 km x 1.8 km, ~half the original AOI)",
    "aoi = gpd.GeoDataFrame(",
    "    {'name': ['demo']},",
    "    geometry=[shapely_box(*AOI_BOUNDS)],",
    "    crs='EPSG:4326',",
    ")",
    "aoi.plot()",
    "plt.title('Demo AOI: Capitol Hill, Washington DC')",
    "plt.show()",
))

CELLS.append(code(
    "# Fetch a recent NAIP scene via geowombat's STAC interface. This",
    "# searches Planetary Computer, signs the URL, clips to the AOI, and",
    "# returns both the DataArray and a GeoDataFrame of the matching",
    "# STAC items (with each item's true scene polygon as its geometry).",
    "from geowombat.core.stac import open_stac",
    "",
    "naip_local = WORK_DIR / 'naip_aoi.tif'",
    "",
    "data, naip_items = open_stac(",
    "    stac_catalog='microsoft_v1',",
    "    collection='naip',",
    "    bounds=AOI_BOUNDS,            # lat/lon (left, bottom, right, top)",
    "    start_date='2021-01-01',",
    "    end_date='2023-12-31',",
    "    max_items=1,                  # take the most recent scene",
    "    epsg=26918,                   # NAD83 / UTM 18N for the DC area",
    "    resolution=0.6,               # NAIP native ground sample distance",
    "    compute=True,                 # eagerly download into memory",
    ")",
    "",
    "# Materialize to disk so later cells can re-open with chunked I/O.",
    "data.gw.save(naip_local, num_workers=4, overwrite=True)",
    "naip_crs = data.gw.crs_to_pyproj",
    "print(f'NAIP scene: {naip_items[\"id\"].iloc[0]}')",
    "print(f'Wrote local AOI clip: {naip_local}')",
    "",
    "# The STAC item carries the actual scene polygon (not just a bbox).",
    "# Intersect with the AOI to get the *valid* coverage area — buildings",
    "# outside this polygon would sit on no-data pixels.",
    "from shapely.geometry import box as shapely_box",
    "aoi_poly_4326 = shapely_box(*AOI_BOUNDS)",
    "valid_polygon_4326 = naip_items.geometry.iloc[0].intersection(aoi_poly_4326)",
))

CELLS.append(code(
    "# Fetch OSM buildings within the NAIP coverage polygon (not the raw",
    "# AOI bbox), so we don't ingest labels in areas with no imagery.",
    "import osmnx as ox",
    "",
    "tags = {'building': True}",
    "buildings = ox.features_from_polygon(valid_polygon_4326, tags=tags)",
    "buildings = buildings[buildings.geometry.type.isin(['Polygon', 'MultiPolygon'])].copy()",
    "buildings['class_name'] = 'building'",
    "print(f'Fetched {len(buildings)} building footprints inside NAIP coverage')",
    "buildings.head(3)",
))

CELLS.append(code(
    "# Reproject buildings into the raster CRS and double-check they fall",
    "# inside the NAIP scene polygon.",
    "buildings_proj = buildings.to_crs(naip_crs)",
    "valid_polygon_naip_crs = (",
    "    gpd.GeoSeries([valid_polygon_4326], crs='EPSG:4326')",
    "      .to_crs(naip_crs).iloc[0]",
    ")",
    "buildings_proj = buildings_proj[",
    "    buildings_proj.intersects(valid_polygon_naip_crs)",
    "].copy()",
    "",
    "# sensor='naip' tells geowombat NAIP's bands are red/green/blue/nir",
    "# (4-band RGBN). Inside this context we can select bands by name,",
    "# and detection helpers also resolve `band_indices` themselves — no",
    "# need to pass `band_indices=[0, 1, 2]` per call.",
    "with gw.config.update(sensor='naip'):",
    "    with gw.open(naip_local, chunks=512) as src:",
    "        print(f'NAIP scene: {src.gw.nrows} x {src.gw.ncols}, '",
    "              f'{src.gw.nbands} bands, {src.gw.cellx:.2f} m')",
    "        fig, ax = plt.subplots(figsize=(10, 10))",
    "        # `.gw.imshow` handles the (band, y, x) -> (y, x, band) reorder",
    "        # and uses the raster's geographic extent automatically.",
    "        (src.sel(band=['red', 'green', 'blue'])",
    "            .gw.imshow(ax=ax, robust=True))",
    "        buildings_proj.boundary.plot(ax=ax, color='yellow', lw=1)",
    "        ax.set_title('NAIP + OSM buildings (truth labels)')",
    "        plt.show()",
))

CELLS.append(code(
    "# Build a YOLO-format training dataset from the NAIP raster + buildings.",
    "# NAIP bands 0,1,2 are R,G,B already 8-bit — no scaling needed. We use",
    "# the `.gw.to_yolo_dataset(...)` accessor so the call stays inside the",
    "# `with gw.open(...) as src:` block, like every other geowombat workflow.",
    "yolo_dir = WORK_DIR / 'naip_buildings_yolo'",
    "",
    "with gw.config.update(sensor='naip'):",
    "    with gw.open(naip_local, chunks=512) as src:",
    "        info = src.gw.to_yolo_dataset(",
    "            labels=buildings_proj,    # vector labels to use",
    "            class_col='class_name',   # column with the class name",
    "            out_dir=yolo_dir,         # where to write the dataset",
    "            tile_size=640,            # tile size in pixels",
    "            overlap=0.1,              # how much tiles overlap (0–0.9)",
    "            val_split=0.2,            # fraction of tiles used for validation",
    "            min_box_pixels=10,        # drop boxes smaller than this",
    "            background_ratio=0.1,     # keep some empty tiles as negatives",
    "            scale=None,               # NAIP is already 8-bit, no rescaling",
    "        )",
    "print(info)",
))

CELLS.append(md(
    "### Inference with pretrained YOLO",
    "",
    "We run `YOLODetector` directly on the NAIP scene. Pretrained COCO",
    "weights have no 'building' class, so we expect very few or no useful",
    "detections — but this verifies the inference pipeline (tile windowing,",
    "cross-tile NMS, pixel→CRS box conversion) end-to-end.",
))

CELLS.append(code(
    "# `YOLODetector` holds the loaded model. `src.gw.detect(detector, ...)`",
    "# is the geowombat-native call site — same shape as `src.gw.predict()`",
    "# for classification.",
    "# Load the model once and reuse it.",
    "det = YOLODetector(weights='yolov8n.pt')",
    "",
    "with gw.config.update(sensor='naip'):",
    "    with gw.open(naip_local, chunks=512) as src:",
    "        preds = src.gw.detect(",
    "            det,",
    "            tile_size=640,            # tile size for inference",
    "            overlap=0.2,              # overlap so objects on tile edges aren't missed",
    "            conf=0.10,                # low threshold: COCO weights don't know buildings",
    "            scale=None,",
    "            nms_iou=0.5,              # how much overlap before duplicates are merged",
    "            progress=True,",
    "        )",
    "print(f'{len(preds)} detections from pretrained YOLO')",
    "preds.head()",
))

CELLS.append(md(
    "### Reading the accuracy output",
    "",
    "Before we compute metrics, a quick glossary — these terms appear in the",
    "tables below and in the per-feature `status` column of the review",
    "GeoPackage.",
    "",
    "**Per-detection / per-truth labels**",
    "",
    "- **TP — True Positive.** A predicted box that overlaps a ground-truth",
    "  box with IoU ≥ the threshold *and* has the correct class. A hit.",
    "- **FP — False Positive.** A predicted box with no matching truth at",
    "  the chosen IoU. A hallucination.",
    "- **FP_class — Wrong-class False Positive.** Predicted box landed in",
    "  about the right place (IoU ≥ threshold against *some* truth) but the",
    "  class label was wrong. Useful to separate 'model can't see it' from",
    "  'model sees it but mislabels it'.",
    "- **FN — False Negative.** A ground-truth box no detection matched.",
    "  A miss.",
    "",
    "**IoU — Intersection over Union.** The area of overlap divided by the",
    "area of union between two boxes. 1.0 = perfect overlap, 0.0 = no",
    "overlap. The IoU threshold (`0.3`, `0.5`, …) controls how strict the",
    "spatial agreement needs to be to count as a match. 0.5 is the standard",
    "PASCAL VOC threshold; 0.3 is more lenient and useful for noisy or very",
    "small targets.",
    "",
    "**Aggregate metrics**",
    "",
    "- **precision = TP / (TP + FP)** — of what the model predicted, what",
    "  fraction was right? Penalizes false alarms.",
    "- **recall = TP / (TP + FN)** — of all the real objects, what fraction",
    "  did the model find? Penalizes misses.",
    "- **F1 = 2 · (precision · recall) / (precision + recall)** — harmonic",
    "  mean of the two; one number that drops if either side is poor.",
    "- **AP — Average Precision.** Sweeps the confidence threshold from",
    "  high to low and integrates the precision-recall curve. A single",
    "  per-class number that captures the precision/recall tradeoff over",
    "  all confidence levels.",
    "- **mAP@0.5** — the mean of per-class AP at IoU ≥ 0.5. The standard",
    "  single-number summary for a detector.",
    "- **mAP@\\[.5:.95]** — average of mAP at IoU thresholds 0.5, 0.55, …,",
    "  0.95. COCO's stricter measure; rewards tightly localized boxes.",
    "- **support** — number of ground-truth boxes for that class (the",
    "  denominator for recall). Small support = noisy estimate.",
    "",
    "Higher is better for everything except the bucket counts (where higher",
    "is better only for TP).",
))

CELLS.append(code(
    "# Accuracy assessment vs. OSM truth. We re-tag predictions as 'building'",
    "# so the comparison is meaningful — pretrained YOLO labels things",
    "# 'car', 'truck', etc., but we just want to see what it *boxed*.",
    "preds_as_building = preds.copy()",
    "preds_as_building['class_name'] = 'building'",
    "",
    "results_pretrained = detection_accuracy(",
    "    predictions=preds_as_building,",
    "    truth=buildings_proj[['class_name', 'geometry']],",
    "    class_col='class_name',",
    "    iou_thresholds=(0.3, 0.5),",
    ")",
    "print('Per-class metrics (pretrained YOLO, no fine-tuning):')",
    "print(results_pretrained['metrics'])",
    "print()",
    "print('Summary:', results_pretrained['summary'])",
    "results = results_pretrained  # alias kept for the cells below",
))

CELLS.append(code(
    "# Visualize TP / FP / FN",
    "with gw.config.update(sensor='naip'):",
    "    with gw.open(naip_local, chunks=512) as src:",
    "        fig, ax = plt.subplots(figsize=(12, 12))",
    "        plot_detections(",
    "            src,",
    "            predictions=results['matched'],",
    "            truth=buildings_proj,",
    "            ax=ax,",
    "            scale=None,",
    "        )",
    "        plt.show()",
))

CELLS.append(code(
    "# Export the review GeoPackage. Open this in QGIS, use the attribute",
    "# form or GoToNextFeature3+ to step through each detection, and fill in",
    "# `reviewer_label` (TP/FP/FN/unclear). Then call recompute_from_review.",
    "review_path = WORK_DIR / 'review.gpkg'",
    "export_for_review(results['matched'], review_path)",
    "print(f'Review file: {review_path.resolve()}')",
    "print('  In QGIS: Open layer → switch to Form view → use',",
    "      '\"GoToNextFeature3+\" or built-in next-feature shortcut.')",
))

CELLS.append(md(
    "## 3. Fine-tune YOLO on the building dataset",
    "",
    "Pretrained COCO YOLO can't recognize buildings. Fine-tuning teaches",
    "it to. We train `yolov8n` (the smallest variant, ~3M parameters) on",
    "the dataset we just built. Settings chosen for CPU-friendliness:",
    "small `imgsz`, small `batch`, modest `epochs`. On a typical laptop",
    "CPU expect a few minutes total; on GPU, well under one minute.",
    "",
    "We send Ultralytics' `runs/` output into `WORK_DIR` so the demo",
    "leaves no clutter at the repo root.",
))

CELLS.append(code(
    "from ultralytics import YOLO",
    "",
    "# Start from COCO weights and fine-tune on our buildings dataset.",
    "yolo_train = YOLO('yolov8n.pt')",
    "_ = yolo_train.train(",
    "    data=str(yolo_dir.resolve() / 'data.yaml'),  # the dataset we just built",
    "    epochs=15,           # how many passes over the data",
    "    imgsz=416,           # training image size",
    "    batch=4,             # batch size (small for CPU)",
    "    name='gw_buildings', # folder name for this run",
    "    exist_ok=True,       # overwrite previous run if present",
    "    verbose=False,",
    "    plots=False,",
    ")",
    "",
    "# Ultralytics writes runs/ relative to its own cwd regardless of the",
    "# project= kwarg, so we read the actual save_dir from the trainer.",
    "best_weights = Path(yolo_train.trainer.save_dir) / 'weights' / 'best.pt'",
    "print(f'Best weights: {best_weights}')",
    "print(f'Exists: {best_weights.exists()}')",
))

CELLS.append(md(
    "### Re-run inference with the fine-tuned model",
    "",
    "Same `YOLODetector` API, just point it at our new weights. We use a",
    "low confidence threshold (`0.05`) because with only ~17 training tiles",
    "and 15 epochs the model is heavily under-trained and hesitant —",
    "production weights would justify a much higher threshold like `0.25`.",
    "",
    "The point of this section is to show the *fine-tuning pipeline* works",
    "end-to-end. The numbers themselves will improve substantially with",
    "more data (a wider AOI), more epochs (50–100), and a larger backbone",
    "(`yolov8s.pt` or `yolov8m.pt`).",
))

CELLS.append(code(
    "det_ft = YOLODetector(",
    "    weights=str(best_weights),   # our fine-tuned weights",
    "    classes=['building'],        # class names for the output",
    ")",
    "",
    "with gw.config.update(sensor='naip'):",
    "    with gw.open(naip_local, chunks=512) as src:",
    "        preds_ft = src.gw.detect(",
    "            det_ft,",
    "            tile_size=416,           # match the training image size",
    "            overlap=0.2,",
    "            conf=0.05,               # short training run, so use a low threshold",
    "            scale=None,",
    "            nms_iou=0.5,",
    "            progress=True,",
    "        )",
    "print(f'{len(preds_ft)} detections from fine-tuned YOLO',",
    "      f'(was {len(preds)} pretrained)')",
))

CELLS.append(code(
    "# Score the fine-tuned predictions",
    "results_ft = detection_accuracy(",
    "    predictions=preds_ft,",
    "    truth=buildings_proj[['class_name', 'geometry']],",
    "    class_col='class_name',",
    "    iou_thresholds=(0.3, 0.5),",
    ")",
    "print('Per-class metrics (fine-tuned YOLO):')",
    "print(results_ft['metrics'])",
    "print()",
    "print('Summary:', results_ft['summary'])",
))

CELLS.append(md(
    "### Before vs. after",
    "",
    "Side-by-side comparison of the pretrained and fine-tuned runs at",
    "IoU ≥ 0.3. Look at TP/FN going up/down for recall and FP for",
    "precision — the F1 column is the single-number summary.",
))

CELLS.append(code(
    "import pandas as pd",
    "",
    "iou = 0.3  # use the more lenient threshold for the comparison",
    "row_pre = results_pretrained['metrics'].loc[(iou, 'building')]",
    "row_ft = results_ft['metrics'].loc[(iou, 'building')]",
    "compare = pd.DataFrame(",
    "    {'pretrained': row_pre, 'fine-tuned': row_ft},",
    ")",
    "compare['delta'] = compare['fine-tuned'] - compare['pretrained']",
    "print(f'Comparison at IoU >= {iou}:')",
    "print(compare.round(3))",
))

CELLS.append(code(
    "# Visualize TP / FP / FN from the fine-tuned run",
    "with gw.config.update(sensor='naip'):",
    "    with gw.open(naip_local, chunks=512) as src:",
    "        fig, ax = plt.subplots(figsize=(12, 12))",
    "        plot_detections(",
    "            src,",
    "            predictions=results_ft['matched'],",
    "            truth=buildings_proj,",
    "            ax=ax,",
    "            scale=None,",
    "        )",
    "        ax.set_title('Fine-tuned YOLO: TP (lime) / FP (red) / FN (magenta)')",
    "        plt.show()",
))

CELLS.append(md(
    "## 4. Refine boxes to polygons with SAM",
    "",
    "Detector output is bounding boxes — fine for counting and",
    "georeferencing, but downstream GIS work usually wants the actual",
    "*footprint*: a polygon that hugs the roof outline, the ship hull,",
    "the storage-tank circle. `SAMRefiner` takes each detected box as a",
    "prompt to Meta's [Segment Anything Model](https://segment-anything.com/),",
    "returns a tight mask, and polygonizes it back into a vector geometry",
    "in the source CRS.",
    "",
    "Requirements:",
    "",
    "```",
    "pip install geowombat[sam]",
    "```",
    "",
    "Plus a one-time checkpoint download. We use `sam_vit_b` (~375 MB)",
    "for speed in this notebook; `sam_vit_l` and `sam_vit_h` are slower",
    "but produce slightly cleaner masks on tricky targets.",
))

CELLS.append(code(
    "# One-time download of the SAM ViT-B checkpoint (~375 MB).",
    "# Cached under WORK_DIR so subsequent runs skip the download.",
    "import urllib.request",
    "",
    "SAM_URL = ('https://dl.fbaipublicfiles.com/segment_anything/'",
    "           'sam_vit_b_01ec64.pth')",
    "sam_ckpt = WORK_DIR / 'sam_vit_b.pth'",
    "if not sam_ckpt.exists():",
    "    print(f'Downloading SAM checkpoint to {sam_ckpt} (~375 MB) ...')",
    "    urllib.request.urlretrieve(SAM_URL, sam_ckpt)",
    "    print('Done.')",
    "else:",
    "    print(f'Using cached checkpoint at {sam_ckpt}')",
))

CELLS.append(code(
    "# Refine the fine-tuned YOLO boxes to building polygons with SAM.",
    "# We feed the top-confidence detections so SAM has clean prompts —",
    "# noisy boxes give noisy masks.",
    "from geowombat.detect import SAMRefiner",
    "",
    "refiner = SAMRefiner(checkpoint=sam_ckpt, model_type='vit_b')",
    "",
    "prompts = (preds_ft",
    "           .sort_values('score', ascending=False)",
    "           .head(30)",
    "           .reset_index(drop=True))",
    "",
    "with gw.config.update(sensor='naip'):",
    "    with gw.open(naip_local, chunks=512) as src:",
    "        polygons = refiner.refine(",
    "            src,",
    "            prompts,",
    "            pad_pixels=12,           # context around each box for SAM",
    "            simplify_tolerance=0.3,  # polygon smoothing, in CRS units (meters)",
    "        )",
    "",
    "print(f'{len(polygons)} refined polygons '",
    "      f'(from {len(prompts)} input boxes)')",
    "polygons.head(3)",
))

CELLS.append(code(
    "# Side-by-side: YOLO rectangle vs. SAM polygon for the same set of",
    "# detections. Look for polygons that track the roof outline instead",
    "# of the bounding rectangle.",
    "with gw.config.update(sensor='naip'):",
    "    with gw.open(naip_local, chunks=512) as src:",
    "        fig, axes = plt.subplots(1, 2, figsize=(20, 10))",
    "        for ax, gdf, title in [",
    "            (axes[0], prompts, 'YOLO boxes (input prompts)'),",
    "            (axes[1], polygons, 'SAM polygons (refined footprints)'),",
    "        ]:",
    "            (src.sel(band=['red', 'green', 'blue'])",
    "                .gw.imshow(ax=ax, robust=True))",
    "            gdf.boundary.plot(ax=ax, color='lime', lw=1.5)",
    "            ax.set_title(title)",
    "            ax.set_axis_off()",
    "        plt.tight_layout()",
    "        plt.show()",
))

CELLS.append(code(
    "# Save the refined polygons for GIS downstream (QGIS, ArcGIS, etc.).",
    "refined_path = WORK_DIR / 'naip_buildings_sam.gpkg'",
    "polygons.to_file(refined_path, driver='GPKG')",
    "print(f'Wrote {refined_path}')",
))

CELLS.append(md(
    "**Tips for getting clean SAM masks**",
    "",
    "- **Prompt quality matters.** SAM uses the box as a prompt, so",
    "  loose, oversized YOLO boxes will produce loose masks. Filter by",
    "  `score` (as above) or use the tighter-fit `oriented=True` OBB",
    "  output from `yolov8*-obb.pt` weights for better prompts.",
    "- **`pad_pixels`** controls how much context SAM sees around each",
    "  box. Too small and SAM may snap to a sub-part of the object; too",
    "  large and it may grab a neighbor. 8–16 px is a good range.",
    "- **`simplify_tolerance`** is in CRS units (meters here). Raise it",
    "  for cleaner-looking outlines, lower it (or set to 0) to preserve",
    "  exact mask edges.",
    "- **Backbone size**: swap `model_type='vit_l'` or `'vit_h'` (and",
    "  the matching checkpoint URL) for finer masks at the cost of",
    "  speed and ~3–7× more memory.",
))

CELLS.append(md(
    "## How to make the fine-tune actually good",
    "",
    "The numbers above are deliberately weak — we trained for 15 epochs",
    "on a tiny AOI just to keep the demo fast. Here's what to change when",
    "you want results that you'd ship, in rough order of payoff:",
    "",
    "1. **Get more training data.** This is by far the biggest lever.",
    "   YOLO needs to see hundreds to thousands of examples of the object",
    "   to learn what it looks like under different lighting, angles, and",
    "   surroundings. Widen the AOI, pull more cities, or merge multiple",
    "   `build_dataset` runs into one folder. A 5× larger label set will",
    "   usually beat any hyperparameter tweak.",
    "",
    "2. **Clean up the labels.** A small set of *accurate* boxes is",
    "   worth more than a large set of sloppy ones. OpenStreetMap is",
    "   crowdsourced and noisy — buildings get demolished, traced",
    "   imprecisely, or sit a few meters off where they actually are. A",
    "   short pass through QGIS removing or fixing the worst examples",
    "   pays off more than another 50 epochs.",
    "",
    "3. **Train longer.** 15 epochs is a sketch. Real fine-tunes run",
    "   50–200 epochs. The training process saves the best checkpoint",
    "   along the way, so longer training rarely hurts — it just costs",
    "   time. Watch the validation mAP curve flatten and stop there.",
    "",
    "4. **Use a bigger model.** We trained `yolov8n` (nano, ~3M",
    "   parameters) because it's fast. Swap to `yolov8s` (small),",
    "   `yolov8m` (medium), or `yolov8l` (large) for steady accuracy",
    "   gains. Each step roughly doubles training time. On a GPU,",
    "   `yolov8s` or `yolov8m` is the sweet spot for aerial imagery.",
    "",
    "5. **Start from satellite-pretrained weights.** We started from",
    "   `yolov8n.pt` (trained on COCO — everyday photos). For overhead",
    "   imagery, **`yolov8n-obb.pt`** is a much better starting point:",
    "   it's pretrained on DOTA, an aerial benchmark with planes,",
    "   ships, vehicles, buildings, harbors, etc. The model already",
    "   knows what bird's-eye-view objects look like — you're just",
    "   teaching it your specific class.",
    "",
    "6. **Tune the tile size.** If your objects are tiny inside the",
    "   tile (e.g. cars in a 1024-px tile), YOLO will struggle to see",
    "   them. As a rule of thumb, an object should be at least ~32",
    "   pixels across after tiling. For dense small objects, shrink",
    "   the tile (256–416 px) or use higher overlap so each object",
    "   gets seen in at least one un-cropped tile.",
    "",
    "7. **Sweep the confidence threshold *after* training.** Don't pick",
    "   `conf=0.05` blindly — once the model is trained, re-run inference",
    "   at several thresholds (0.1, 0.25, 0.5) and look at the",
    "   precision/recall trade-off via `detection_accuracy`. Higher",
    "   thresholds give fewer, more reliable detections; lower ones",
    "   catch more but include more false positives. Pick the spot",
    "   that matches what your downstream use case cares about.",
    "",
    "8. **Add hard negatives.** If the model keeps flagging the same",
    "   non-building things (parking lots, dark roofs), give it some",
    "   *empty* tiles of those features in training. The",
    "   `build_dataset(background_ratio=0.2, ...)` argument keeps a",
    "   fraction of empty tiles in the dataset for exactly this reason.",
    "",
    "9. **Use the QGIS review loop.** After inference,",
    "   `export_for_review` writes a GeoPackage you open in QGIS to",
    "   tag each detection as TP / FP / FN by hand. Feed the",
    "   corrected file back into `recompute_from_review` for honest",
    "   numbers — and use the FP/FN polygons as **additional training",
    "   data** in the next round. Two or three cycles of this usually",
    "   matter more than any single training tweak.",
    "",
    "If you do (1) and (5) and nothing else, expect a large jump.",
    "Everything else past that is fine-grained tuning.",
))

CELLS.append(md(
    "## Summary — the geowombat-native idiom",
    "",
    "Everything in this notebook fits the same shape as the rest of",
    "geowombat. Inside a `with gw.open(...) as src:` block:",
    "",
    "- `src.gw.to_yolo_dataset(labels, class_col=..., out_dir=...)` tiles",
    "  the raster + labels into a YOLO training corpus on disk.",
    "- `src.gw.detect(detector, ...)` runs tiled, windowed inference with",
    "  cross-tile NMS and returns a georeferenced `GeoDataFrame`.",
    "",
    "Outside the block, in `gw.detect`:",
    "",
    "- `YOLODetector` (Ultralytics) and `TorchGeoDetector` (Faster R-CNN /",
    "  RetinaNet) are the detector classes you pass into `src.gw.detect`.",
    "- `gw.detect.predict`, `gw.detect.fit`, `gw.detect.fit_predict` are",
    "  module-level wrappers that mirror `gw.ml.fit` / `predict` /",
    "  `fit_predict` for classification.",
    "- `build_dataset` is the function form of `src.gw.to_yolo_dataset`.",
    "- `SAMRefiner` (requires `geowombat[sam]`) refines boxes to polygon",
    "  masks using each box as a SAM prompt — see Section 4 for the",
    "  end-to-end example on the fine-tuned building detections.",
    "- `detection_accuracy` computes per-class precision/recall/F1/AP at one",
    "  or more IoU thresholds and returns a *review-ready* GeoDataFrame.",
    "- `export_for_review` writes a GeoPackage for QGIS attribute-form",
    "  review; `recompute_from_review` recomputes metrics after a human has",
    "  labeled the review file.",
    "",
    "When `gw.config.update(sensor='rgb')` (or `'bgr'`) is active, the",
    "accessor methods derive the RGB band indices from the active config —",
    "you don't need to pass `band_indices=[...]` per call.",
))

NOTEBOOK = {
    "cells": CELLS,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.11",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}


if __name__ == "__main__":
    out_path = Path(__file__).parent / "object_detection.ipynb"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(NOTEBOOK, f, indent=1)
    print(f"Wrote {out_path}")
